### ISSUE TITLE
[Bug]: Pause in syncing causes sync status to update to last synced

### ISSUE THREAD

**Issue by kadisonm** [sboesen/remotely-sync#102]
### What happened?

If an item takes longer to sync then the status bar will update to the last synced, then get set back to the status bar.

Need to refactor sync status to use the same lastSynced as Sync on Remote (they're both saving essentially the same thing). I should be able to take a look and fix this. :)

### What OS are you using?

Windows

### What remote cloud services are you using?

Dropbox

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
> If an item takes longer to sync then the status bar will update to the last synced

Awesome! I am not sure what this means exactly but sounds like you have a plan to fix it - appreciate all the effort you've put in here!!

**Comment by kadisonm** [comment]
Sorry I'll elaborate aha. Believe this only really happens on a lower concurrency, but I found the 'start syncing' and 'finish syncing' stopped for a second or two (which I presume is it taking longer to upload). During this the status bar turned back to 'last synced x minutes ago'. Once the item finished syncing it went back to showing the sync status.

I suspect that something is updating the status bar during this but I need to have a look.

**Comment by sboesen** [comment]
Ah, gotcha, I have seen that in the pas I think. Not really sure why that behavior happens.
