### ISSUE TITLE
[Bug]: New PQueue is created on every operation

### ISSUE THREAD

**Issue by kadisonm** [sboesen/remotely-sync#104]
### What happened?

A new PQueue is created on every operation (folder creation, delete, upload) causing the status bar to show 3 seperate queues.

Accumilate all the files needed for upload on a single queue. I'll do some testing on this.

### What OS are you using?

Windows

### What remote cloud services are you using?

Dropbox

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by kadisonm** [comment]
Actually now that I'm thinking about it, shouldn't the status bar only be updated for upload/downloads? @sboesen

**Comment by sboesen** [comment]
I think if you have a lot of folder creations (usually a one-time problem) that should be tracked in the status bar, too - I don't think this is a bulk operation

But there shouldn't be a queue created for each operation. That is odd..

**Comment by kadisonm** [comment]
> But there shouldn't be a queue created for each operation. That is odd..

It's because it loops through each array (operation), then creates a queue for that array and adds uploads to the queue. But this causes the status bar to show three queues in order.

> I think if you have a lot of folder creations (usually a one-time problem) that should be tracked in the status bar

I'll have a look at updating the status bar for folder creations and upload/downloads but not deletions.
