### ISSUE TITLE
[Feature Request]: Better indication of start up Sync On Remote

### ISSUE THREAD

**Issue by kadisonm** [sboesen/remotely-sync#110]
### What feature are you suggesting?

I notice it's a little vague what's happening on mobile with Sync On Remote.

Maybe on load it can check for remote changes and if none are found notify with "Vault is up to date." So the user knows it doesn't need to sync.

Otherwise, indicate that a sync is running "Remote changes found, running sync." or something similar.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Good idea!

**Comment by sboesen** [comment]
@kadisonm I think this is closed, reopen if you disagree!
