### ISSUE TITLE
[Bug]: Status bar not showing on plugin install

### ISSUE THREAD

**Issue by kadisonm** [sboesen/remotely-sync#120]
### What happened?

Status bar doesn't show on plugin install and has to be disabled and enabled to see.

Additionally there is a bit of delay after syncing finishes where the status bar doesn't update to 'Synced less than a minute ago'.

I can fix these minor issues. :)

### What OS are you using?

Windows

### What remote cloud services are you using?

Dropbox

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by kadisonm** [comment]
Status bar not showing on install should be fixed. 

As for the other issue with the update delay after syncing. At the end of syncing it gets the metadata's modified time and sets it as the last synced. Turns out getting the mTime takes a while making it seem like the status bar wasn't updating. Need to somehow refactor this in the future.

**Comment by sboesen** [comment]
Thank you so much for updating this! Really appreciate your contributions :)

**Comment by kadisonm** [comment]
No worries!
