### ISSUE TITLE
[Feature Request]:  Add the status bar on mobile

### ISSUE THREAD

**Issue by YIRU69** [sboesen/remotely-sync#122]
### What feature are you suggesting?

https://forum.obsidian.md/t/css-to-show-status-bar-on-mobile-devices/77185/4

I find the way can show status bar on mobile. I try to show the sync status on status. But it display none.

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by YIRU69** [comment]
The effect of displaying the status at a specific location on the phone can be achieved by modifying this CSS.

**Comment by kadisonm** [comment]
Hi, I'll look into the css. Do you know of any examples of this being done I could look at?

Also we have an issue for this open at #43, but I'll change that one to be just the sync history. The status bar can be tracked here.

As of current the only 'solution' is to go to settings > mobile > Configure mobile Quick Action and setting the command to 'Get sync status'. This makes it so when you slide the top of the screen down, it'll show a notification with the status.

**Comment by kadisonm** [comment]
Wow, that's cool it works for me. Just cuts off for phones. I wonder if it could be adapted to only show the sync status.

Regardless, showing the status on mobile should be easy to fix. I'll do it as soon as possible.

Thanks for making this issue!

**Comment by kadisonm** [comment]
@YIRU69 Thanks for the guidance. This should be added in the next update.

I managed to make it work without the CSS snippet so the plugin will show the status bar on mobile automatically. You will have to enable the status bar in Remotely Sync's settings on your mobile device first though.

So glad this is finally resolved. I haven't been able to properly test it on my phone, only through emulating on desktop. So please let me know if there are any bugs.

**Comment by YIRU69** [comment]
@kadisonm I tested it, but the result was not ideal. I used the default skin, and the display status of this plugin would block the function buttons at the bottom of the phone. Maybe I didn't explain it clearly, and I hope you can improve it and make it appear in an appropriate position.

**Comment by kadisonm** [comment]
I just noticed this too. I'll take a look and see if I can modify the css to make the status bar higher. At the moment it should be just doing what the css snippet above does. I'll check if there is a difference between them and if there is, I'll try and figure out why.

**Comment by kadisonm** [comment]
Moved the issues to #124.
