### ISSUE TITLE
[Bug]: Mobile status bar hides bottom buttons and elements get readded

### ISSUE THREAD

**Issue by kadisonm** [sboesen/remotely-sync#124]
### What happened?

I've noticed that backlinks and other status bar elements get readded when opening a new note. Requires a restart to clear them again.

Another issue mentioned by @YIRU69 is the status bar covers the buttons on the bottom of the screen.

### What OS are you using?

Android

### What remote cloud services are you using?

Dropbox

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by kadisonm** [comment]
Should be fixed in the next update alongside the default settings for it. 

If you're on computer then by default:
  status bar -> enabled 
  showing only last synced -> disabled
If you're on mobile then by default 
  status bar -> disabled
  showing only last synced -> enabled

**Comment by sboesen** [comment]
This should be fixed in 0.4.47, but users updating may need to tweak their settings on mobile - not sure the fixes flipped the settings correctly if they were already set.

**Comment by sboesen** [comment]
![Screenshot 2024-03-09 at 7 18 30 PM](https://github.com/sboesen/remotely-sync/assets/248703/0945919e-3d1a-4259-be39-039191a06b61)
I think it's better, but I'm seeing it covering the buttons on iOS still. Maybe needs more CSS tweaking?

**Comment by kadisonm** [comment]
Whoops my mistake. It looks like it changes depending on the device. I hardcoded the value to move it up by and assumed it would be consistent since it looked right on my pc and phone.

Will have to try and see if I can get the value from the css somehow.

**Comment by YIRU69** [comment]
I'll share my thoughts; why not change the display method? For instance, display an icon that, when clicked, will expand to reveal information, and after a period of time, it will automatically contract back into a button. This approach doesn't require such high CSS adaptations for different devices. I didn't know much about CSS at the time, but now I understand that this can be implemented.

**Comment by kadisonm** [comment]
It's not a bad idea but it will require getting the height of the nav bar at the bottom to place the button above it anyways. I made a PR that fixes the status bar for all devices (hopefully) and it turned out to be a simple fix anyways.

Wouldn't be opposed to adding a button if there was enough people who want it. I feel like the status bar would do just fine though.

**Comment by sboesen** [comment]
> Wouldn't be opposed to adding a button if there was enough people who want it. I feel like the status bar would do just fine though.

+1. @YIRU69 please feel free to open a feature request, happy to merge if it is implemented or take a stab at it when I get more free time to contribute further.

**Comment by kadisonm** [comment]
Odd, it seems like on my phone (android) the status bar isn't shifting. Weird how it does on my computer though. 

I'll make another PR soon and will test on my phone peoperly before merging this time. I suspect the is phone check isn't returning true for my device, but will need to have a look.

On a side note, can anyone confirm if it is working on iOS?

**Comment by kadisonm** [comment]
Looks like this not working is likely due to #132.
