### ISSUE TITLE
[Feature Request]: Sync on save with .obsidian folder

### ISSUE THREAD

**Issue by kadisonm** [sboesen/remotely-sync#26]
### What feature are you suggesting?

I'm not entirely sure if this is possible. However, I have a homework plugin that stores data in the json file. As of current sync on save does not automatically sync changes here, so I have to manually sync.

If this is possible, would there be able to have a feature where specific files or folders are watched? Or the whole .obsidian itself?

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
<img width="791" alt="Screenshot 2023-11-19 at 12 48 11 AM" src="https://github.com/sboesen/remotely-secure/assets/248703/29f3b2f5-f3fd-4449-bba4-31150042aa06">
Hello, I believe this feature is here - turn on "Sync Config Dir" and it will sync your .obsidian directory entirely. Please let me know if it's not working for you, thanks!

**Comment by kadisonm** [comment]
Hi,
That is on but what I mean is that when one of the plugin's data.json file is changed then sync on save doesn't detect it. 
I'm not sure if it is possible to watch for changes within the .obsidian folder, but with my current set up I rely purely on sync on save and don't bother with manual syncing. 

But this means if I go into my vault, change a plugin setting, then close it, then it isn't synced since I didn't edit a file.

**Comment by sboesen** [comment]
Ahh, I see. Thanks for clarifying! I didn't read that very carefully, sorry about that. You definitely stated that just fine originally hehe.

I think this is definitely possible, but will mean updating our sync on save implementation which [currently only scans the current file every second](https://github.com/sboesen/remotely-secure/blob/master/src/main.ts#L919-L944). 

I think this is actually worth doing in general as it looks like (based on my code review) sync on save might actually miss changes if the user switches between files quickly enough, and I don't think that is ideal behavior.

Total changes required for this feature, then, IMO:

- Sync on save should periodically scan lastModified time for all local files in the Vault
- Sync on save should optionally (if sync .obsidian config is enabled) scan the .obsidian folder for changes, too

**Comment by sboesen** [comment]
Added issue #27 which will help implement this feature.

**Comment by kadisonm** [comment]
> Ahh, I see. Thanks for clarifying! I didn't read that very carefully, sorry about that. You definitely stated that just fine originally hehe.

All good, I could've been more specfic. 

Would checking the lastModified time of all files each second bring performance issues? Maybe instead of checking each file individually, the vault's root folder could be checked instead. If this is possible.

**Comment by sboesen** [comment]
I'm not sure, curious to benchmark this. I don't really have an intuition for how long the `getSyncPlan` method takes to run, especially over a larger plan.

If it's slow we can probably refactor it to include only the mtime with an additional option.
<img width="210" alt="Screenshot 2023-11-19 at 6 19 53 PM" src="https://github.com/sboesen/remotely-secure/assets/248703/d8afeb59-ab87-4796-a539-92ec1fe9234b">
I don't think checking the folder modification time would work, here is a screenshot of my folder with an older modification time than the .DS_Store file - looks like the folder updates when a new file is created (`touch foo`) but not when modified (`echo a > foo`) on MacOS.

**Comment by sboesen** [comment]
Pull requests definitely welcome, might be a while until this is added due to the lift required.

**Comment by kadisonm** [comment]
Ah okay, that's all good then. I'm not too fussed with performance since it would probably be miniscule anyways.
I would love to work on this myself, but I don't entirely understand how the plugin works so it'd probably be best in your hands.

Thanks for all the work by the way!

**Comment by sboesen** [comment]
> I would love to work on this myself, but I don't entirely understand how the plugin works so it'd probably be best in your hands.

All good, but I definitely am learning it in pieces myself :) Still some things to dive into. Happy to contribute back!

**Comment by sboesen** [comment]
Added in 0.4.22. Keep in mind the plugin rename may delay updates from showing up in the community plugin list, but manual installation is still possible.

**Comment by kadisonm** [comment]
Thanks for this by the way, just got to test it and it's great!

**Comment by sboesen** [comment]
No problem! It is not super performant, but I added it at a 10x delay for what your sync on save setting is. Way smarter ways to do sync, but this was the easiest for now.
