### ISSUE TITLE
[Bug]: Too many api requests

### ISSUE THREAD

**Issue by Royage888** [sboesen/remotely-sync#30]
### What happened?

When the document is saved in real time, too many api requests are initiated. Under the same conditions, this is nearly three to four times more than using rs.

### What OS are you using?

macOS

### What remote cloud services are you using?

S3

### Version of the plugin

0.4.17

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Did this get resolved?
