### ISSUE TITLE
[Feature Request]: Advice on “The plugin tries to sync on after each file save”

### ISSUE THREAD

**Issue by lyiton** [sboesen/remotely-sync#45]
### What feature are you suggesting?

While I was still editing, saverun was started, which I don't think is a correct synchronization solution. And when I set it to every second, synchronization will already start every time I pause after typing. In this way, synchronization is going on all the time, which greatly consumes network resources. I think we can add a judgment condition, and synchronize only when the file has not changed for more than a few seconds (that is, it has been determined to be saved).

And autorun and saverun are easy to conflict. When I set the time to the lowest, whoever performs it first will easily conflict. I think these two functions should not be used at the same time, or the values ​​of the two functions cannot be set to the lowest at the same time.

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Agreed, minimizing syncs for single character changes would be ideal and a good feature request, thanks for opening this issue!

> And autorun and saverun are easy to conflict. 

This sounds like a (separate) bug. What are your settings to trigger these conflicts? I'll open a new bug with those details.

**Comment by MartinJDavis93** [comment]
Here, I completely disagree with you. As I understand it, by 'SaveRun', you mean 'Sync on Save'. The whole idea of this feature is to track changes in the file in real-time, including the input/deletion of each character. Yes, this feature is far from flawless, but it works well. Not worse than in OneNote, which I used before. And if you increase the time from 1 second to several seconds, the whole point of this feature will be lost. If you need more time than 1 second, there is automatic synchronization. In general, in this regard, the plugin is now excellent, offering several different options and combinations that everyone can tailor to their needs.

The same applies to simultaneously enabling 'Sync on Save' feature and autosync. What is the conflict? Everything works correctly. Whichever function reacts faster to synchronization will perform the synchronization. I haven't seen any abnormal battery drain. Everything is as usual. The appropriateness of using them simultaneously is for each user to decide; no one forces you to use them together or use them at all. If you don't like it, turn it off; if you want it, turn it on.

**Comment by lyiton** [comment]
Thank you for your answer!

What I want to say is that if you set autorun to once every second, you can already track changes in real time, so why do you need to set saverun again?

Maybe I didn't think it through well, welcome to discuss.

**Comment by kadisonm** [comment]
> What I want to say is that if you set autorun to once every second, you can already track changes in real time, so why do you need to set saverun again?

Yeah I kind of thought about this as well. But went the opposite route and decided to disable autorun completely and only use sync on save. Purely because I don't need obsidian syncing every second if I leave it idle. I do also think they conflict though, but I'm not really sure of a solution since it kind of depends on individual preference.

It wouldn't be bad to make a note of it in the settings to tell the user maybe.

**Comment by lyiton** [comment]
I think I should add a condition to my previous explanation. 

> And autorun and saverun are easy to conflict.

Conflicts occur during editing.

When in editing state, it is possible that both autorun and saverun will be triggered at the same time.

When idle, the two will not conflict because there will only be autorun.

**Comment by lyiton** [comment]
> I realized - I think this is actually basically a feature we already have. If you want sync on save to be every 5 seconds that's an option. It won't be exactly precise (it's checking for changes every 5-10 seconds vs. waiting 5 seconds, so if you want it to wait about 5 seconds probably set it to 10 seconds instead).

Is the time interval here calculated from the last synchronization completion or from the last synchronization start?

Based on my observations, I think it's since the last sync started. This will bring about a new problem. Synchronization takes time (about 2-3S), so if it is set to every 1 second, Sync on save will continue.

I think the ideal sync interval should be after the last sync has completed.

**Comment by sboesen** [comment]
> I think I should add a condition to my previous explanation.
> 
> > And autorun and saverun are easy to conflict.
> 
> Conflicts occur during editing.
> 
> When in editing state, it is possible that both autorun and saverun will be triggered at the same time.
> 
> When idle, the two will not conflict because there will only be autorun.

This shouldn't happen because only one sync will run at a time, shouldn't matter if it's automatic or manual or some combination of Sync on Save + automatic + manual. Are you experiencing sync conflicts due to simultaneous sync?

In theory could be a race condition checking the syncstatus.


> > I realized - I think this is actually basically a feature we already have. If you want sync on save to be every 5 seconds that's an option. It won't be exactly precise (it's checking for changes every 5-10 seconds vs. waiting 5 seconds, so if you want it to wait about 5 seconds probably set it to 10 seconds instead).
> 
> Is the time interval here calculated from the last synchronization completion or from the last synchronization start?
> 
> Based on my observations, I think it's since the last sync started. This will bring about a new problem. Synchronization takes time (about 2-3S), so if it is set to every 1 second, Sync on save will continue.
> 
> I think the ideal sync interval should be after the last sync has completed.

I checked just now and the [code for sync on save](https://github.com/sboesen/remotely-secure/blob/master/src/main.ts#L980-L995) runs every second regardless of the setting. What it does is:
1) if the time since the last modification for the current file is < sync on save time (say 10 seconds):
2) schedule a sync for approximately the sync on save time (so 10 seconds) minus the time it's been since the file was modified. If we're a second late, it runs for 9 seconds
3) if a sync is already scheduled, do nothing

**Comment by MartinJDavis93** [comment]
> Thank you for your answer!
> 
> What I want to say is that if you set autorun to once every second, you can already track changes in real time, so why do you need to set saverun again?
> 
> Maybe I didn't think it through well, welcome to discuss.

Currently, the minimum auto-sync time is 5 seconds, not 1. I mentioned before that syncing every second is already too frequent.

> Regarding 'Sync on Save' and the shortened time for automatic synchronization. Even in this short interval of slightly more than a day, I have already encountered several times that synchronization did not occur in automatic mode. But it's not a problem; it's just the time interval that is genuinely necessary for synchronization, because a certain waiting time is needed for the synchronization of changes. And so that you can make changes and close the application, most likely, you will not get into the synchronization window and the changes made will not be synchronized accordingly. Even if the time for automatic synchronization is reduced to 1 second (which, in my opinion, is already absurd), we still have to wait a few seconds before we can close the application. Therefore, the habit of manually starting synchronization will not go away. And the 'Sync on Save' feature and the shortened time for automatic synchronization are more pleasant additions, just in case if you forget to start synchronization manually, there is a better chance of getting at least partially synchronized changes.

As for the feasibility and the ability to set a shorter interval for auto-sync, I partially explained it here; I don't want to repeat myself.

> As for 'Sync on Save', judging by the description, it tracks changes in the file and similar things, which theoretically could break if Obsidian developers decide to make changes in this regard. Therefore, automatic synchronization in this regard is more versatile and resilient.

I believe that this variability practically covers each user's usage scenario, which is great in my opinion. How to manage it is a personal decision. For now, I have enabled auto-sync every 5 seconds and the 'Sync on Save' feature to see how they work together. I agree that it might not be entirely practical, but in this scenario, auto-sync works more frequently for me, and it has no significant impact on my battery. Over time, I may disable 'Sync on Save' if I encounter any issues because auto-sync is a higher priority for me due to its logic and simplicity of operation.

**Comment by kadisonm** [comment]
> Currently, the minimum auto-sync time is 5 seconds, not 1

Yeah I realised this, wrote 1 as mistake. But what I said still applies to me. I don't want my vault syncing every 5 seconds if I leave obsidian in the background especially because my laptop has awful battery.

> Which theoretically could break if Obsidian developers decide to make changes in this regard

I doubt this would break though unless Obsidian decides to completely rework the TFile class. I wouldn't worry about this though, as I doubt Obsidian would just cut things out their API. At most they'd probably deprecate the TFile class but not remove it entirely to avoid this. Let me know if my understanding of this is wrong though.

**Comment by MartinJDavis93** [comment]
> > Currently, the minimum auto-sync time is 5 seconds, not 1
> 
> Yeah I realised this, wrote 1 as mistake. But what I said still applies to me. I don't want my vault syncing every 5 seconds if I leave obsidian in the background especially because my laptop has awful battery.
> 
> > Which theoretically could break if Obsidian developers decide to make changes in this regard
> 
> I doubt this would break though unless Obsidian decides to completely rework the TFile class. I wouldn't worry about this though, as I doubt Obsidian would just cut things out their API. At most they'd probably deprecate the TFile class but not remove it entirely to avoid this. Let me know if my understanding of this is wrong though.

Well, auto-sync at 5 seconds is just the minimum value. If it doesn't suit you, set the value that suits you, or disable auto-sync altogether. This is my scenario, it suits me, it is clear that it cannot suit everyone. So, the variety of settings is designed for everyone to configure it as convenient for them. I don't see any problem here.

I haven't delved into how it's all set up in detail. I'm just an ordinary user who doesn't delve into all the nuances of how a particular program or service works. But probably there's no need to delete or modify TFile; even seemingly insignificant changes to it could disrupt the plugin's operation. Auto-sync at 5 seconds is entirely suitable for my needs. Others can use or combine parameters as they see fit. It's their choice.

**Comment by kadisonm** [comment]
> Well, auto-sync at 5 seconds is just the minimum value. If it doesn't suit you, set the value that suits you, or disable auto-sync altogether.  

Yeah I already have I was just stating my solution to this "What I want to say is that if you set autorun to once every second, you can already track changes in real time, so why do you need to set saverun again?"

> I don't see any problem here.

There wasn't a problem don't worry, I'm aware everyone has different set ups to their need. That's what make this plugin so good.

> But probably there's no need to delete or modify TFile; even seemingly insignificant changes to it could disrupt the plugin's operation.

That's fair.

**Comment by lyiton** [comment]
> I checked just now and the [code for sync on save](https://github.com/sboesen/remotely-secure/blob/master/src/main.ts#L980-L995) runs every second regardless of the setting. What it does is:
> 
> 1.if the time since the last modification for the current file is < sync on save time (say 10 seconds):
> 2.schedule a sync for approximately the sync on save time (so 10 seconds) minus the time it's been since the file was modified. If we're a second late, it runs for 9 seconds
> 3.if a sync is already scheduled, do nothing

Okay, I know. Maybe it's my problem, the conflict I mentioned above isn't really a "conflict". I just think so logically, and the actual plug-in execution will not conflict. Thanks!

**Comment by kadisonm** [comment]
> I just think so logically, and the actual plug-in execution will not conflict. Thanks!

It's okay I had the same thought too. 😆
I'm sure clarification somewhere wouldn't be a bad idea though.

**Comment by sboesen** [comment]
Closing as I think the issue was addressed, but please reopen and call out any action required if I missed it, thanks!
