### ISSUE TITLE
[Bug]: Fix sync status jitter when syncing files concurrently

### ISSUE THREAD

**Issue by sboesen** [sboesen/remotely-sync#46]
### What happened?

Concurrency settings affect the numerator in the sync progress display - that is, (1/3) <-- the 1, not the 3.

Figure out a way to sync the current sync item when concurrently synchronizing individual items.

~~Latest update changed how the sync status is computed, and we have a report (#44) that this total sync item number is going down, which is odd. TODO: Figure out why that is (if I can reproduce the issue) and fix it~~

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
@lyiton have you experienced the number on the right of the "/" (`1/100`) changing in the middle of a sync after that initial sync? I'm wondering if that still happening for you and if you have any thoughts on how I could reproduce the issue locally or if it's inconsistent. Thanks!

**Comment by sboesen** [comment]
Refocusing this issue on the concurrency problem which seems like the main issue. I did a code review and the array we use to compute the total items is never changed after it's created, which leads me to think it can't go down in the middle of a sync.

**Comment by sboesen** [comment]
That's actually not a bug (maybe depends on interpretation) - Folders are individually synchronized, so if you have 1000 folders it won't just be one upload, it'll be 1000 upload operations. There might be a smarter way to synchronize these, but definitely higher priority items including a deeper refactor of the sync process.

**Comment by lyiton** [comment]
Okay, I understand. Thank you for your reply!

**Comment by sboesen** [comment]
No problem at all! I could see hiding it if it's a small folder count, but synchronization would "freeze" and I don't think that's a great experience. I personally prefer tracking each upload operation separately to see what's happening in more detail. That could just be me, though!

The concurrency issue I definitely want to fix, though.

**Comment by geerteltink** [comment]
I noticed this issue as well. Is it possible that each synced file is running async and it updates the first number once it is done? Meaning, a bigger file might set the total synced files back if a smaller file was uploaded before.

I would expect that there is a function call which increases the total synced files, not forcing that file 10 was synced. 

NOTE: I didn't check the code yet, just assuming something like this happens.

**Comment by sboesen** [comment]
Yes, exactly. The [upload code](https://github.com/sboesen/remotely-sync/blob/master/src/sync.ts#L1395) throws all the jobs into a [p-queue](https://www.npmjs.com/package/p-queue) if `concurrency` is set `> 1`, and p-queue manages the concurrency - I don't think any of the sync tracking code is thread-safe, which worked OK on the console (because nobody ever saw the total) but now that we display it that makes it a bit more obvious something is bugged!

**Comment by sboesen** [comment]
Potential fix in 0.4.26, limited testing but we're using a better approach for this (IMO). If this doesn't work will need to go deeper, but I didn't have a chance to setup a vault with the test files shared & remote sync store.

**Comment by kadisonm** [comment]
I noticed while trying to set up my vault again that on the initial sync the status bar is stuck on (852/867) the whole time. Even though files are clearing still syncing in the console.

**Comment by sboesen** [comment]
Should be fixed in 0.4.37, please reopen if the issue persists!
