### ISSUE TITLE
[Bug]: Vault syncing 171 files after no changes

### ISSUE THREAD

**Issue by kadisonm** [sboesen/remotely-sync#51]
### What happened?

The status bar is jittering and saying there is 171 files to sync on every sync. I have turned on debug mode and it is actually syncing a lot of files, even though no changes have been made to them.

Additionally my obsidian themes and plugin deletions aren't syncing, so everytime I reopen they reinstall. But file changes are still syncing.

![080lGfRKzY](https://github.com/sboesen/remotely-secure/assets/134670047/b2efad9e-d5b1-4de9-9029-d61c617736a8)

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.4.21

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Could be related to #46

**Comment by sboesen** [comment]
Thx for the report/gif! Really helps

**Comment by kadisonm** [comment]
I ran a few syncs to check how many files were syncing.
I worked the number out by filtering the console for something with no result, which shows the amount hidden. Then I subtracted the amount hidden by the 'finished' filter hidden.

Test 1: 1991 - 1090 = 901
Test 2: 1994 - 1093 = 901
Test 3: 1994 - 1093 = 901

Not sure why the total changed the first time, but it seems to be syncing 901 files every time. Not sure if this is expected functionality though, I assume the plugin only syncs changed files but I could be wrong. Let me know if this is normal.

**Comment by lyiton** [comment]
I've also experienced status bar jitter (I mean the increment of the numerator is choppy) and resyncing, but it's not a guaranteed occurrence. And the resynchronization is really happening, it is not showing an error, I saw the PUT and GET requests from the OSS console.

**Comment by sboesen** [comment]
Related to #44 for sure.

**Comment by sboesen** [comment]
The jittering is related to #44, will address in that issue. The "syncing lots of files without any changes" is a completely separate issue - could you please take a look at your console logs and let me know what the "decision" is for the files which aren't modified but are syncing? This will help narrow down why items are being sync'd if they shouldn't be.

Modifying this issue's title to focus on syncing unnecessary items.

<img width="539" alt="Screenshot 2023-12-02 at 9 19 38 AM" src="https://github.com/sboesen/remotely-sync/assets/248703/ee3b767b-d26d-490d-b753-9d9200c87c6a">

**Comment by kadisonm** [comment]
Not sure if this relates but I updated the plugin and got this.

![image](https://github.com/sboesen/remotely-sync/assets/134670047/5208c102-8433-4f1b-9a60-9dc70b463039)

And it's repeating getJson until it hits that error then starts over again. So it's stuck in a loop.

**Comment by geerteltink** [comment]
I noticed this today, when I connected another device. As expected, it downloads all the files. On the next start, it starts uploading all files, even though there are no changes. And on the older connected device you can see that it downloads files again, but they are the same.

**Comment by sboesen** [comment]
I've noticed this behavior, too, I think the current timestamp checking has its limits. I'm keeping this issue open as a bug, but I think #40 really captures the real fix which is doing some sort of hash based comparison.

**Comment by sboesen** [comment]
Closing this issue in favor of #60 due to the details, but this is the same issue.
