### ISSUE TITLE
[Bug]: Plugin id mismatch

### ISSUE THREAD

**Issue by kadisonm** [sboesen/remotely-sync#54]
### What happened?

Hi just letting you know that when the plugin is clicked on in the community plugins, it can't be found because I presume Obsidian's json file is out of date.

You can close this since it will fix, but just letting you know. 

### What OS are you using?

Android

### What remote cloud services are you using?

OneDrive for personal

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Just updated in the latest release, but still not showing as fixed for me. Keeping this issue open until it's resolved, thanks for opening.

Looks like it'll be a bit awkward until the name change is official.

**Comment by sboesen** [comment]
Looks like it synced now! Closing issue.
