### ISSUE TITLE
[Bug]: Synchronization error：password_not_matched

### ISSUE THREAD

**Issue by ddvcx** [sboesen/remotely-sync#57]
### What happened?

When I use WebDAV synchronization, Got error message: "password_not_matched," I have ensured that the username and password is correct. 
Here is the log file：
```text
[2023-12-05T11:12:46+08:00] password is blank?  true  remote has metadata?  false
[2023-12-05T11:12:46+08:00] ERROR! MESSAGE: password_not_matched, STACK: Error: password_not_matched
    at Rx.syncRun (plugin:remotely-secure:180:2022)
```

### What OS are you using?

Android

### What remote cloud services are you using?

webdav

### Version of the plugin

0.4.24

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Hey, thanks for filing the bug and sorry you're getting this error :( 

I just checked and it's working for me, which is odd.

Could you please try deleting the folder on your webdav server and synchronizing with the same device twice in a row?

Do any of the devices sync after you get this error, or do they all error?

**Comment by ddvcx** [comment]
Thank you for your reply.
I conducted the following tests.
1. After this error occurs, other Android devices also encounter the same issue.
2. The error disappears after deleting all files on WebDAV.

**Comment by xppx99** [comment]
Hello, 

I have the same problem, in iOS and also Mac. 

@sboesen , when you sugested "Could you please try deleting the folder on your webdav server and synchronizing with the same device twice in a row?", what folder are you referring to? 

Thanks

**Comment by sboesen** [comment]
To clarify I'm saying try to delete the folder on your remote sync service (dropbox, webdav, s3, or onedrive) and re-sync.

Syncing twice on a row from the same device should work, and is a decent test that the encryption password (if used) is identical - if fails to work after a successful sync then it's probably an issue with the plugin.

@xppx99 are you using encryption? If so, are you sure the password is identical on both devices?

I've removed all password checking functionality; getting `password_matched` means the decryption failed, which is probably due to a password mismatch.

**Comment by xppx99** [comment]
I'm not using encryption. 

Followed your suggestion:
1. Delete the folder and re-synced. 
2. The first sync return an error on 1 file, did not understand why. Retried it a few times and the same resulted the same error 
3. Activated the sync of the config folder, and the sync "magically" worked. 
4. confirmed also on my iphone. 
5. When activating "./trash" sync, returns a different error (but I think is unrelated with this topic):
```
remotely-secure-1702415299722: abort sync, triggerSource=manual, error while syncing

trash/: Request failed, status 405
```

**Comment by sboesen** [comment]
Hmm, glad the syncing is working but sorry you're getting an odd error syncing the trash folder. Let me open that as a new issue

**Comment by borg1622** [comment]
> To clarify I'm saying try to delete the folder on your remote sync service (dropbox, webdav, s3, or onedrive) and re-sync.

@sboesen Could you add this information to the [WebDAV section of the usage instructions](https://github.com/sboesen/remotely-sync#webdav) as well, please?
Or put it as general advice regardless of the storage backend type.

P.S.: In the [S3 bucket section](https://github.com/sboesen/remotely-sync#s3) there is already a hint.

**Comment by sboesen** [comment]
Done! Good suggestion, added a general troubleshooting section.
