### ISSUE TITLE
[Enhancement]: Display user friendly error for connection issues

### ISSUE THREAD

**Issue by kadisonm** [sboesen/remotely-sync#59]
### What happened?

I was syncing on mobile and it was taking a long time. It then showed this:

![Screenshot_20231207_085550_md obsidian_edit_70290063915836](https://github.com/sboesen/remotely-sync/assets/134670047/2ea6fb34-c640-4500-95ad-2101102476a9)

Not sure if this means anything.

### What OS are you using?

Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.4.25

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Hmm, I suspect this is either 1) a large file timing out or 2) poor network connection. The large file could be a metadata file if it has grown, remotely save had some reports about that. Does this keep happening?

**Comment by sboesen** [comment]
Can you share the error on the console (expanding the object)? Need to modify the exception handling code (main.ts:301 ish) to look for that error type in particular.

**Comment by kadisonm** [comment]
I'm not entirely sure I can reproduce because it stopped happening right after I refreshed the app.

**Comment by sboesen** [comment]
Sounds good, I'll close this one for now but if you can trigger it again and post the log (expanding the object logged) I can try to wrap it and provide a better error message. For now I think it's not a big deal

**Comment by kadisonm** [comment]
Hi is this related? I'm getting this after moving two files and renaming them.

![image](https://github.com/sboesen/remotely-sync/assets/134670047/bfbe1681-0337-48c1-b5e7-e21ced9dfdc2)

**Comment by kadisonm** [comment]
Please feel free to move this to a seperate issue if it is unrelated.

**Comment by sboesen** [comment]
Looks separate! Will move it
