### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'adapter')

### ISSUE THREAD

**Issue by Araeos** [sboesen/remotely-sync#63]
### What happened?

After setting up Dropbox auth and choosing an E2E encryption password I tried my first sync.

This always fails with the following error:
![image](https://github.com/sboesen/remotely-sync/assets/6041246/7938536f-2419-4e7b-8776-5600ba999ec0)

### What OS are you using?

Windows

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.4.27

### Version of Obsidian

v1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by oconr** [comment]
I am also getting this exact same issue appear when I try to sync

Plugin version: 0.4.27
Obsidian version: 1.4.16
OS: macOS Sonoma 14.2 & Windows 11
Remote cloud: Digitalocean Spaces (S3 compatible)

**Comment by sboesen** [comment]
Thanks for the bug report and sorry about the error. Taking a look

**Comment by sboesen** [comment]
Looks like it errored when syncing metadata due to the metadata file not existing locally, sorry about that! Should be fixed in 0.4.28 - Please reopen if the issue persists.
