### ISSUE TITLE
[Bug]: Initial Sync Status Bar Stuck

### ISSUE THREAD

**Issue by kadisonm** [sboesen/remotely-sync#68]
### What happened?

On initial sync to OneDrive the status bar shows syncing in groups and then switching to (841/846) and getting stuck there. Once sync ends it goes back to showing the last synced.

![kz97Xp6al2](https://github.com/sboesen/remotely-sync/assets/134670047/fb99aef3-759d-42e9-a018-d11179c32406)

Gif of it happening. (gif ends when it gets to (841/846)

The files are syncing to my OneDrive though, which I can see on the OneDrive and in the Obsidian console.

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.4.28

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by lyiton** [comment]
I also encountered this problem in the S3 service. This problem seems to occur in versions 0.4.27, 0.4.28, and 0.4.29. After I returned to 0.4.26, it became normal.

**Comment by sboesen** [comment]
Last [changes I made](https://github.com/sboesen/remotely-sync/compare/0.4.25...0.4.26) to the sync progress bar were in 0.4.26, so odd that one is working normally for you.

I'll look into this and see if I can reproduce, but I am not currently able to reproduce this locally currently on 0.4.29 with S3:

![Screen Recording 2023-12-13 at 11 45 55 AM](https://github.com/sboesen/remotely-sync/assets/248703/0a81b147-8341-45e5-a34c-ce1f232babcf)

For troubleshooting, please try set the "skip large files" setting to 5 MB and see if that gets the issue working. Could be our handling of larger files that is getting sync "stuck".

<img width="530" alt="Screenshot 2023-12-13 at 11 47 48 AM" src="https://github.com/sboesen/remotely-sync/assets/248703/58651c5b-99a8-4687-a7e2-8da6be001702">

**Comment by kadisonm** [comment]
Hi,

I'm having the same issues with Dropbox  and setting the Skip Large Files to 5mb. I can't attach a gif because I keep getting '429 (Too Many Requests)' so it's taking longer to sync.

This might only happen on larger vaults since mine is showing up in groups of 4, 13, then 64 then smaller groups again. So maybe try syncing 1000 or so test files and see if it happens.

**Comment by YIRU69** [comment]
The same issues on version [0.4.28](https://github.com/sboesen/remotely-sync/releases/tag/0.4.28) 0.31. And the version 0.29 is worked.

**Comment by sboesen** [comment]
Definitely reproduced this issue (or something like it) - number starts low, then increases which doesn't make sense to me. That will help with testing! 

Will try to isolate the code change.

**Comment by YIRU69** [comment]
@sboesen Happy new year! I still use the plugin on version 0.29 because of the issue. Could you fix it?

**Comment by sboesen** [comment]
@YIRU69 happy new year! Unfortunately I haven't had a chance to look into this one further and there are some functionality issues I feel are at a higher priority (preventing sync for certain configurations) but will try to resolve this one ASAP when I get a chance. Sorry about the delay!

**Comment by sboesen** [comment]
Should be fixed in 0.4.37, please reopen if the issue persists!
