### ISSUE TITLE
[Bug]: The second stage alert message disappears.

### ISSUE THREAD

**Issue by lyiton** [sboesen/remotely-sync#71]
### What happened?

Manually click sync when running automatically, and the second stage alert message disappears. After 1/2 ends, there will normally be 2/2.

![PixPin_2023-12-14_21-01-22](https://github.com/sboesen/remotely-sync/assets/76651858/9fcfb9f1-b1d7-4bd1-89e2-a89298aedf6e)

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.4.31

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Odd - thanks for filing!

**Comment by kadisonm** [comment]
This is because it's set not to show notices when the status bar is enabled, but this blocks the 2/2 notice. I'll try fixing it.
