### ISSUE TITLE
[Bug]: Onedrive sync failure after auth. Password_not_matched 

### ISSUE THREAD

**Issue by mingxin-zheng** [sboesen/remotely-sync#80]
### What happened?

I tried to use this plugin to replaced the "Remotely Sync". After setting it up (install and auth on Onedrive), I saw a folder with the vault name appear in my Onedrive Apps folder. But when I put a folder in the folder and tried to sync something from the folder just created to my phone, I got the following error:
![image](https://github.com/sboesen/remotely-sync/assets/18563433/7fc56e71-99db-46ae-9d8c-4255e0ddff8e)

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.4.31

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by mingxin-zheng** [comment]
Update:
Tried the "remotely sync" and it doesn't have this issue. Could this be some missing steps after sync/auth?

**Comment by kadisonm** [comment]
Hi, just check that you have the same password set on both devices. If you're not using a password then try confirming nothing on both devices and trying again. Otherwise there must be a bug.

**Comment by mingxin-zheng** [comment]
Hi @kadisonm , thanks for the reply. I think the problem shouldn't be the password, because
- Authentication of Onedrive was done externally in a browser, and only after that succeeds, the Obsidian (plugin) will reopen and proceed
- I tried a couple of times and it's the same.
- I used the "remotely save" and it doesn't have this issue.

**Comment by kadisonm** [comment]
All good! Sounds like there is probably a bug then. As far as I know, OneDrive probably has the most issues since it hasn't been worked on as much as dropbox and s3. We'll have to wait and see if @sboesen can fix it.

**Comment by sboesen** [comment]
Hi @mingxin-zheng sorry you are having issues syncing with Remotely Sync - could you post a screenshot of console logs from the desktop version of Obsidian? 

Does this error only occur on mobile (or do you only use mobile devices to sync this folder)?

You can also check if the app folder in OneDrive has a `_remotely-secure-metadata-on-remote.json` file.

For what it's worth I was able to sync a brand new vault in my OneDrive app folder, definitely want to understand what is going wrong here. Thank you for filing the bug!

**Comment by mingxin-zheng** [comment]
Hi @sboesen , thanks for the follow up! 

I am using the mobile version (iPhone) and see the issue. I will give it another pass later today after work.

Just in case if I can reproduce the bug, is there any log I can port from the mobile version?
