### ISSUE TITLE
[Bug]: ERR_UNSAFE_PORT when using webdav with a port hosted on 10080

### ISSUE THREAD

**Issue by crotoc** [sboesen/remotely-sync#81]
### What happened?

I setup a sftpgo service on a server hosting webdav on 10080. When I use the address and the port to test the connection in remotely sync. It threw ERR_UNSAFE_PORT error. Is there a way to use the unstandard port of webdav. Thanks!

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.4.31

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
It looks like this port 10080 is specifically blocked by some browsers, see this [list](https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/net/base/port_util.cc#107). Could you please try a different port by editing the configuration file as described in the [sftpgo documentation](https://github.com/drakkan/sftpgo/blob/main/docs/howto/getting-started.md#enable-webdav-service)?

Interesting bug report, thanks for filing!

**Comment by crotoc** [comment]
Bing! The problem is solved. I change to 7090, it can be synced successfully!

**Comment by sboesen** [comment]
That's great to hear! Glad it was an easy fix.
