### ISSUE TITLE
[Bug]: Sync on Remote tries to sync multiple times

### ISSUE THREAD

**Issue by kadisonm** [sboesen/remotely-sync#98]
### What happened?

I'm finding that after detecting remote changes 'password is blank?  false  remote has metadata?  false' gets printed around 10 times then it runs multiple syncs at the same time.

![image](https://github.com/sboesen/remotely-sync/assets/134670047/3b91855d-6dd9-4634-8036-20bc783cfab6)

Not entirely sure why or how it is managing to sync multiple times at once.

At the end the metadata sync is all bunched up.

![image](https://github.com/sboesen/remotely-sync/assets/134670047/37695c4c-81dc-4d92-bb2d-0d9eac438f29)

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.4.36

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by kadisonm** [comment]
Additionally if I turn Sync on Save, Sync on Remote off and only manually sync. Somehow the metadata is synced before the end of step 3?

This only happens when I reset the metadata file I believe. Found this trying to uninstall the original Remotely Save which I can't seem to remove even after resetting the metadata.

![Obsidian_pBJSeNNRSj](https://github.com/sboesen/remotely-sync/assets/134670047/c5a3dbea-95f8-4f43-a2a6-9cb11c912d72)

And then the metadata is synced again at the end.

![Obsidian_OYOrz5ULNH](https://github.com/sboesen/remotely-sync/assets/134670047/1a4abb05-fc89-4748-9235-6becb5622d74)

This might be one of the causes that Sync on Remote is running multiple.

**Comment by sboesen** [comment]
Interesting... maybe sync config dir is syncing your remotely save plugin and preventing deleting it?

Does it work with just remotely sync?

**Comment by kadisonm** [comment]
I have sync config dir on. If I disable it will it delete the .obsidian on the remote? I think everytime I delete Remotely Save it thinks my local doesn't have it and resyncs it back in. Not sure why. This is kind of a seperate issue though.

> Does it work with just remotely sync?
Not sure what you mean, sorry.

**Comment by sboesen** [comment]
Yeah you need to delete your metadata file with the reset dev setting after disabling and this has to be disabled on all devices where it is enabled - related to the issue where we can't track deletes outside obsidian.
