### ISSUE TITLE
[Bug]: Failed to read the 'headers' property from 'ResponseInit': String contains non ISO-8859-1 code point

### ISSUE THREAD

**Issue by landandan** [sboesen/remotely-sync#99]
### What happened?

[2024-01-09T10:05:05+08:00] remotely-save-1704765905347：中断同步，同步来源=manual，出错阶段=syncing
[2024-01-09T10:05:05+08:00] ERROR! MESSAGE: 
    Error: 常用docker/: Failed to construct 'Response': Failed to read the 'headers' property from 'ResponseInit': String contains non ISO-8859-1 code point.
        at eval (plugin:remotely-save:320:65306)

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.34

### Version of Obsidian

1.5.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Hello, looks like this is an issue with the Remotely Save plugin. Can you confirm you are using Remotely Sync?

**Comment by landandan** [comment]
sorry,Sent to the wrong place
